# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: RunTest
  workspace:
    clean: all
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Docker@2
    displayName: Docker Login
    inputs:
      command: login
      containerRegistry: "Docker Registry"
  - script: |
      docker run -v $(pwd):/src --workdir /src --env SEMGREP_APP_TOKEN=$(SEMGREP_APP_TOKEN) returntocorp/semgrep-agent:v1 semgrep-agent 